config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :books, only: [:edit, :index, :new, :show, :create, :destroy, :update]
  resources :users, only: [:edit, :new, :show, :index, :create, :update]
  get 'home/about' => 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true,length: { minimum: 1 }
  validates :body, presence: true, length: { in: 1..200 }
#   validates :profile_image, presence: true
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}

  has_one_attached :profile_image

def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top, :about]
   before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
     user_path(current_user.id)
   end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :ensure_correct_user, only: [:edit, :update]
  def new
    @user = User.new
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if@book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
     @books = Book.all
     @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
    
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  def update
    @book = Book.find(params[:id])
    @user = User.new
    if@book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end


  private
  def book_params
    params.require(:book).permit(:title, :body, :profile_image)
  end

  def ensure_correct_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @user = User.new
    @book = Book.new
    if @user.save
      flash[:notice] = "welcome!,user successfully."
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def create
    # @User = User.new(user_params)
    # @User.user_id = current_user.id
    # @User.save
    # redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
    flash[:notice] = "You have updated user successfully."
  end

  def update
    @user = User.find(params[:id])
  if@user.update(user_params)
    redirect_to user_path
  else
    render :edit
  end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
<div class="col-md-3">
  <div></div>
</div>

<div class="col-md-6" >
<h1>Editing Book</h1>
<%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Opinion</h4>
  <%= f.text_area :body %>

</br>
  <%= f.submit 'Update Book', class: "btn btn-success" %>

  <% end %>
<th>
  <%= link_to "Show", book_path(@book.id) %>|
  <%= link_to "Back", books_path %>
</th>
</div>

<div class="col-md-3">
  <div></div>
</div>
</div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">

  <%= render 'users/list', user: @user, book: @book %>
<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
<% @books.each do |book| %>
 <table class="table table-striped">
     <th><%= link_to user_path(book.user.id) do %>
       <%= image_tag book.user.get_profile_image(100,100) %>
       <% end %></th>
    <th><%= link_to book_path(book.id) do %>
       <%= book.title %>
       <% end %>
    </th>
    <th><%= book.body %></th>
<% end %>
</tr>
  </thead>
</table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class="container">
<div class="row">
<%= render 'users/list', book: @book_new, user: @user %>
<div class="col-md-8 offset-md-1">
<h1>Book detail</h1>

<table class="table table-striped">
<thead>
<tr>
 <th><%= image_tag @user.get_profile_image(100,100) %></th>
 <th><%= link_to user_path(@user.id) do %>
       <%= @user.name %>
       <% end %>
    </th>
  <th><%= @book.title %></th>
  <th><%= @book.body %></th>

  <% if @book.user == current_user %>
  <th><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></th>
  <th>
      <%= link_to "Destroy", book_path(@book), method: :delete,class: "btn btn-danger", "data-confirm" => "Are you sure?" %></th>
  <% end %>
</tr>
</thead>
</table>
</div>
</div>
  </div>

app/views/homes/about.html.erb
<h1>Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>

<footer>CopyRight Infratop.inc</footer>

app/views/homes/top.html.erb
<!DOCTYPE html>


<%= flash[:notice] %>
<div class="container">
  <div class="row">
<div class="col-md-3">
  <div></div>
</div>

<div class="col-md-6">
<h1>welcome to <i class="fa-solid fa-book"></i>Bookers !!</h1>

<h3>
  In<i class="fa-solid fa-book"></i>Bookers,</br>

you can share and exchange your opinions , inpressions , and emotions</br>

about various books!</br>
</h3>

      <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block" %>
      </br>
      </br>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block" %>
    <%= yield %>
</div>

<div class="col-md-3">
  <div></div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta charset="UTF-8">
    <link rel="stylesheets/application" href="application.scss"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/b046e99ada.js" crossorigin="anonymous"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
    <header class="shadow-sm">
    <h3><%= link_to root_path, class: 'text-white' do %>Bookers<% end %></h3>
       <nav class="navbar navbar-expand-lg navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
       <%= link_to user_path(current_user.id), class: 'text-white' do %><i class="fa-solid fa-house"></i>Home&emsp;<% end %>
       </li>
       <li class="nav-item">
       <%= link_to users_path, class: 'text-white' do %><i class="fa-solid fa-users"></i>Users&emsp;<% end %>
       </li>
        <li class="nav-item">
       <%= link_to books_path, class: 'text-white' do %><i class="fa-solid fa-book-open"></i>Books&emsp;<% end %>
       </li>
        <li class="nav-item">
       <%= link_to destroy_user_session_path, class: 'text-white', method: :delete do %><i class="fa-solid fa-right-from-bracket"></i>Log out&emsp;<% end %>
        </li>
      <% else %>
      <li class="nav-item">
       <%= link_to root_path, class: 'text-white' do %><i class="fa-solid fa-house"></i>Home&emsp;<% end %>
       </li>
       <li class="nav-item">
    <%= link_to home_about_path, class: 'text-white' do %><i class="fa-solid fa-link"></i>About&emsp;<% end %>
    </li>
     <li class="nav-item">
    <%= link_to new_user_registration_path, class: 'text-white' do %><i class="fa-solid fa-user-plus"></i>Sign up&emsp;<% end %>
    </li>
     <li class="nav-item">
    <%= link_to new_user_session_path, class: 'text-white' do %><i class="fa-solid fa-right-to-bracket"></i>Log in&emsp;<% end %>
    </li>
    <% end %>
    </ul>
    </div>
    </nav>
  </header>
  <body>
    <%= yield %>
  </body>
</br>
</br>
<footer>CopyRight Infratop.inc</footer>
</html>

app/views/users/_list.html.erb
<div class="col-md-3">
<h1>User info</h1>
<%= image_tag user.get_profile_image(100,100) %>

<table class="table table-striped">
  <thead>
  <tr>
 <div><th>name</th> <th><%= user.name %></th></div>
<table class=" table-striped">
<th>introduction</th><th><%= user.introduction %></th>
</tr>
  </thead>
  </table>

</br>
<% if user == current_user %>
<%= link_to edit_user_path(current_user.id), class: "btn btn-secondary btn-block" do %><i class="fa-solid fa-user-gear"></i><% end %>
<% else %>
<%= link_to edit_user_path(user.id), class: "btn btn-secondary btn-block" do %><i class="fa-solid fa-user-gear"></i><% end %>
<% end %>

 <h2>New book</h2>
  <%= form_with model: book,url: books_path do |f| %>

  　<h4>Title</h4>
  　<%= f.text_field :title %>

  　<h4>Opinion</h4>
  　<%= f.text_area :body %>

</br>
  　<%= f.submit 'Create Book', class: "btn btn-success" %>

  <% end %>
  </div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
<div class="col-md-3">
  <div></div>
</div>

<div class="col-md-6" >
<h1>User info</h1>

<%= form_with model: @user do |f| %>

  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.file_field :profile_image, accept: "image/*" %>

  <h4>Introduction</h4>
  <%= f.text_area :introduction %>
   </br>
  　<%= f.submit 'Update User', class: "btn btn-secondary" %>

<% end %>
</div>

<div class="col-md-3">
  <div></div>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
<%= render 'users/list', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
<h1>Users</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>image</th>
    <th>name</th>

<% @users.each do |user| %>
<table class="table table-striped">
  <th><%= image_tag user.get_profile_image(100,100) %></th>
  <th><%= user.name %></th>
<th><%= link_to "Show",  user_path(user.id) %></th>
<% end %>
</tr>
  </thead>
</table>
</div>
</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container">
<div class="row">
<%= render 'users/list', book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table table-striped">
<thead>
<tr>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th>Title</th>
<th>Opinion</th>
<% @books.each do |book| %>
<table class="table table-striped">
  <th><%= link_to user_path(@user.id) do %>
    <%= image_tag @user.get_profile_image(100,100) %>
    <% end %>
    </th>
  <th><%= link_to book_path(book.id) do %>
       <%= book.title %>
       <% end %>
    </th>
  <th><%= book.body %></th>
<% end %>
</tr>
  </thead>
</table>
</div>
</div>